project:
  type: website

website:
  title: "R Screencasts"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

