project:
  type: website

website:
  title: "R on Demand"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - content_pages/Plastic Waste.qmd 

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

